networks:
  kumulus:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432" #Remover em Prod
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - kumulus

  jboss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jboss_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - kumulus
