networks:
  kumulus:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432" #Remover em Prod
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - kumulus

  jboss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jboss_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - kumulus
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_SERVICE_NAME: "your-service-name"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=your-service-name"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - kumulus

