networks:
  kumulus:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - kumulus

  jboss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jboss_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - kumulus

  jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - "16686:16686"  # Interface Web do Jaeger
      - "14268:14268"  # API HTTP para recebimento de traces
      - "14250:14250"  # gRPC para recebimento de traces
      - "6831:6831/udp" # Protocolo UDP para recebimento de traces
    networks:
      - kumulus